# Generated by Django 5.1.5 on 2025-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_planograma', models.CharField(max_length=255)),
                ('loja', models.CharField(max_length=100)),
                ('secao', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('previsao', models.DateField(blank=True, null=True)),
                ('execucao', models.BooleanField(default=False)),
                ('data_registro', models.DateField(auto_now=True)),
                ('pdf', models.FileField(upload_to='planogrmas_pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='planogramas',
        ),
    ]
