# Generated by Django 5.1.5 on 2025-01-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogramas', '0002_planograma_delete_planogramas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planograma',
            name='pdf',
            field=models.FileField(upload_to='planogramas_pdfs/'),
        ),
    ]
